name: "Multi level pipeline"

on:
    push:
        branches:
            - main
            - test
    pull_request:
        branches:
            - main

jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "running on main push"
              run: echo "Running on mater push"
    
    on-pull_request:
        runs-on: ubuntu-latest
        steps:
            - name: "running on main pull"
              run: echo "Running pull request"